### ISSUE TITLE
Translates until it finds a dot

### ISSUE THREAD

**Issue by PericlesTheo** [pawurb/termit#11]
Hey there, awesome gem!!

I came across the following:

```
termit en es "Yeah really good. How are you?"
=> Sí realmente bueno.
```

Is this the desired behaviour?

To overcome the above I did

```
termit en es "Yeah really good, How are you?"
=> Sí realmente bueno, ¿Cómo estás?
```

Cheers

**Comment by pawurb** [comment]
I will just replace dots with comas automatically and works fine. Released as `2.11.2`. Enjoy :)
