### ISSUE TITLE
No ability to translate from/to several languages

### ISSUE THREAD

**Issue by bogem** [pawurb/termit#15]
![2015-09-11 17 53 06](https://cloud.githubusercontent.com/assets/13235519/9820994/dd61f272-58d0-11e5-9130-3ca7148948cc.png)

**Comment by pawurb** [comment]
I want to keep this tool simple, and see no need to translate into several languages at the same time.

**Comment by bogem** [comment]
Not at the same time
You didn't understood me
I can't translate from Traditional Chinese to English, for example
Because there is limit in your program that length of the language code must be 2 or 4, but length of the language code of Traditional Chinese is 5

**Comment by pawurb** [comment]
Support for other languages was added in `2.13.0`

**Comment by bogem** [comment]
Good
Thanks!
