### ISSUE TITLE
Chinese -t

### ISSUE THREAD

**Issue by rpietro** [pawurb/termit#20]
Trying to get termit to say sentences in Chinese. I tried the following:

    ➜  ~ termit en zh-CHS hello -t
    => 你好
    TERMIT: Looks like you provided invalid options, or speech synthesis is not supported for this language.

Is simplified Chinese really not supported? Btw, great software!

**Comment by pawurb** [comment]
Hello. Thanks for your intrest in termit. I added handling for your case and released it as 3.8.0. Enjoy ;)
