### ISSUE TITLE
Google Translate: Document has moved

### ISSUE THREAD

**Issue by mabstorm** [pawurb/termit#9]
The text_response_handler.rb now is crashing.

> gems/termit-2.0.8/lib/termit/text_response_handler.rb:24:in `extract_translation': >undefined method`split' for nil:NilClass

Looking into the root cause, the text being passed to it is now a 302 error as below, and it should be a simple URL fix in theory:

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>

<H1>302 Moved</H1>

The document has moved
<A HREF="http://ipv4.google.com/sorry/IndexRedirect?continue=http://translate.google.com/translate_a/t?client=t&amp;sl=en&amp;tl=es&amp;hl=pl&amp;sc=2&amp;ie=UTF-8&amp;oe=UTF-8&amp;prev=enter&amp;ssel=0&amp;tsel=0&amp;">here</A>.
</BODY></HTML>

**Comment by p-o-t-s** [comment]
Hello, pawurb.
The other day, has been updated from an older version you have installed (version does not remember ...) to 2.10.2 in mid last spring.
I also, a similar error occurs.

termit/text_response_handler.rb:22:in `extract_translation': undefined method `split' for nil:NilClass (NoMethodError)

**Comment by pawurb** [comment]
I fixed it and released as `2.11.1`

**Comment by p-o-t-s** [comment]
amazing! 
I'm happy because they know and love the termit.
Thank you.
